# Generated by Django 5.2.16 on 2026-07-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='institution',
            field=models.CharField(blank=True, help_text='School, University, or Organization', max_length=255, null=True),
        ),
    ]
