# Generated by Django 5.2.16 on 2026-07-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_icon',
            field=models.CharField(default='default', help_text='Selected preset icon identifier (e.g. cat, fox, robot)', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_type',
            field=models.CharField(choices=[('upload', 'Uploaded Photo'), ('icon', 'Preset Icon'), ('google', 'Google Profile Photo')], default='icon', help_text='Source of the avatar: upload, icon, or google', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Short bio or about me', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, help_text='City, Country', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, help_text='Social links: github, linkedin, twitter URLs'),
        ),
        migrations.AddField(
            model_name='user',
            name='website_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
