# Generated by Django 5.2.16 on 2026-07-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_location_remove_user_social_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='volunteer_status',
            field=models.CharField(choices=[('not_applied', 'Not Applied'), ('pending', 'Pending Approval'), ('approved', 'Approved Volunteer'), ('rejected', 'Rejected')], default='not_applied', max_length=20),
        ),
    ]
