# Generated by Django 5.2.16 on 2026-07-24 12:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public verification identifier — this is the access boundary', unique=True)),
                ('recipient_name_snapshot', models.CharField(max_length=255)),
                ('course_title_snapshot', models.CharField(max_length=500)),
                ('pdf_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('pdf_sha256', models.CharField(blank=True, help_text='SHA-256 checksum of the generated PDF for integrity verification', max_length=64, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('failed', 'Failed'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoke_reason', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='certificates', to='courses.course')),
            ],
            options={
                'db_table': 'certificates',
                'ordering': ['-issued_at'],
            },
        ),
    ]
