# Generated by Django 5.2.16 on 2026-07-24 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('certificates', '0001_initial'),
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='certificate', to='enrollments.enrollment'),
        ),
    ]
