# Generated by Django 5.2.16 on 2026-07-28 19:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_initial'),
        ('courses', '0001_initial'),
        ('enrollments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('background_image_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('logo_image_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('signature_image_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('custom_positions', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'certificate_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='certificate',
            name='unique_certificate_per_user_course',
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='course_title_snapshot',
            new_name='title_snapshot',
        ),
        migrations.AddField(
            model_name='certificate',
            name='cert_type',
            field=models.CharField(choices=[('individual', 'Individual Award / Certificate'), ('program', 'Program Certificate'), ('course', 'Course Certificate')], default='individual', max_length=20),
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='role_snapshot',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificate', to='enrollments.enrollment'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='pdf_sha256',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('failed', 'Failed'), ('revoked', 'Revoked')], default='generated', max_length=20),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='verification_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public verification identifier', unique=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='certificates.certificatetemplate'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['verification_uuid'], name='idx_certificates_ver_uuid'),
        ),
    ]
