# Generated by Django 5.2.16 on 2026-07-28 19:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Program', 'Program'), ('Event', 'Event'), ('Workshop', 'Workshop'), ('Campaign', 'Campaign'), ('Volunteer Opportunity', 'Volunteer Opportunity')], default='Volunteer Opportunity', max_length=50)),
                ('available_positions', models.JSONField(blank=True, default=list)),
                ('eligibility_criteria', models.TextField(blank=True, default='Profile Completion = 100%')),
                ('required_skills', models.JSONField(blank=True, default=list)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('deadline', models.DateField()),
                ('total_seats', models.PositiveIntegerField(default=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('completed', 'Completed'), ('draft', 'Draft')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('applied_position', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('waiting_list', 'Waiting List'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='activities.activity')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_applications',
                'ordering': ['-applied_at'],
                'unique_together': {('activity', 'applicant')},
            },
        ),
    ]
